{
    "a": {
        "com":[],
        "dep":["b", "c", "d"]
    },
    "b": {
        "com": [],
        "dep": []
    },
    "c": {
        "com": [],
        "dep": ["d"]
    },
    "d": {
        "com": [],
        "dep": []
    },
    "e": {
        "com": [],
        "dep": ["g", "f", "q"]
    },
    "g": {
        "com": [],
        "dep": []
    },
    "f": {
        "com": [],
        "dep": []
    },
    "q": {
        "com": ["echo Putting on socks."],
        "dep": []
    }
}